import { User, Project, Risk, RiskAction } from "@/types/risk";

export const mockUsers: User[] = [
  { id: "1", name: "João Silva", email: "joao.silva@empresa.com", role: "Admin" },
  { id: "2", name: "Maria Santos", email: "maria.santos@empresa.com", role: "Coordenador" },
  { id: "3", name: "Carlos Oliveira", email: "carlos.oliveira@empresa.com", role: "Gestor" },
  { id: "4", name: "Ana Costa", email: "ana.costa@empresa.com", role: "Gestor" },
  { id: "5", name: "Pedro Almeida", email: "pedro.almeida@empresa.com", role: "Gestor" },
];

export const mockProjects: Project[] = [
  {
    id: "prj-alpha",
    code: "PRJ-ALPHA",
    name: "Expansão Unidade Norte",
    risksCount: 12,
    criticalPercentage: 25,
    delayedActions: 3,
    lastImport: "2025-10-10",
    assignedUsers: ["3", "4", "5"],
  },
  {
    id: "prj-beta",
    code: "PRJ-BETA",
    name: "Modernização IT",
    risksCount: 8,
    criticalPercentage: 12.5,
    delayedActions: 1,
    lastImport: "2025-10-15",
    assignedUsers: ["3", "5"],
  },
];

const createAction = (
  id: string,
  strategy: RiskAction["strategy"],
  executor: string,
  status: RiskAction["status"],
  daysOffset: number
): RiskAction => {
  const today = new Date();
  const start = new Date(today);
  start.setDate(start.getDate() + daysOffset);
  const end = new Date(start);
  end.setDate(end.getDate() + 30);
  
  return {
    id,
    strategy,
    description: `Implementar medidas de ${strategy.toLowerCase()} para o risco identificado`,
    executor,
    plannedStart: start.toISOString().split('T')[0],
    plannedEnd: end.toISOString().split('T')[0],
    status,
    comments: status === "Atrasada" ? "Aguardando aprovação do orçamento" : undefined,
  };
};

export const mockRisks: Risk[] = [
  {
    id: "risk-001",
    projectId: "prj-alpha",
    type: "Técnico",
    phase: "Execução",
    disc: "ENG",
    seq: 1,
    code: "ALPHA-ENG-001",
    discipline: "Engenharia Civil",
    subject: "Fundações",
    title: "Atraso na entrega de estacas pré-moldadas",
    cause: "Fornecedor único com capacidade limitada de produção",
    description: "Risco de atraso no cronograma devido à dependência de um único fornecedor de estacas, com capacidade de produção limitada que pode não atender aos picos de demanda do projeto.",
    dimension: "Ambos",
    probabilityInitial: 4,
    severityScheduleInitial: 4,
    severityCapexInitial: 3,
    levelScheduleInitial: "Alto",
    levelCapexInitial: "Médio",
    levelGeneralInitial: "Alto",
    probabilitySchedule: 70,
    optimisticSchedule: 10,
    likelySchedule: 20,
    pessimisticSchedule: 35,
    weightedAverageSchedule: 21.67,
    expectedValueSchedule: 15.17,
    optimisticCapex: 50000,
    likelyCapex: 120000,
    pessimisticCapex: 250000,
    weightedAverageCapex: 128333,
    expectedValueCapex: 89833,
    probabilityResidual: 2,
    severityScheduleResidual: 3,
    severityCapexResidual: 2,
    levelScheduleResidual: "Médio",
    levelCapexResidual: "Baixo",
    levelGeneralResidual: "Médio",
    owner: "Carlos Oliveira",
    status: "Monitorando",
    actions: [
      createAction("act-001-1", "Mitigar", "Carlos Oliveira", "Em Execução", -5),
      createAction("act-001-2", "Transferir", "Ana Costa", "Planejada", 10),
    ],
    createdAt: "2025-09-15",
    updatedAt: "2025-10-16",
  },
  {
    id: "risk-002",
    projectId: "prj-alpha",
    type: "Financeiro",
    phase: "Planejamento",
    disc: "FIN",
    seq: 2,
    code: "ALPHA-FIN-002",
    discipline: "Financeiro",
    subject: "Orçamento",
    title: "Variação cambial no equipamento importado",
    cause: "Flutuação da moeda estrangeira",
    description: "Equipamentos críticos serão importados e o aumento da cotação do dólar pode impactar significativamente o CAPEX do projeto.",
    dimension: "CAPEX",
    probabilityInitial: 5,
    severityScheduleInitial: 2,
    severityCapexInitial: 5,
    levelScheduleInitial: "Baixo",
    levelCapexInitial: "Crítico",
    levelGeneralInitial: "Crítico",
    probabilitySchedule: 80,
    optimisticSchedule: 0,
    likelySchedule: 5,
    pessimisticSchedule: 15,
    weightedAverageSchedule: 6.67,
    expectedValueSchedule: 5.34,
    optimisticCapex: 200000,
    likelyCapex: 500000,
    pessimisticCapex: 900000,
    weightedAverageCapex: 516667,
    expectedValueCapex: 413333,
    probabilityResidual: 3,
    severityScheduleResidual: 2,
    severityCapexResidual: 3,
    levelScheduleResidual: "Baixo",
    levelCapexResidual: "Médio",
    levelGeneralResidual: "Médio",
    owner: "Ana Costa",
    status: "Aberto",
    actions: [
      createAction("act-002-1", "Mitigar", "Ana Costa", "Atrasada", -10),
      createAction("act-002-2", "Transferir", "Pedro Almeida", "Planejada", 5),
    ],
    createdAt: "2025-09-20",
    updatedAt: "2025-10-15",
  },
  {
    id: "risk-003",
    projectId: "prj-beta",
    type: "Técnico",
    phase: "Implementação",
    disc: "TI",
    seq: 1,
    code: "BETA-TI-001",
    discipline: "Tecnologia",
    subject: "Migração de Dados",
    title: "Perda de dados durante migração de sistemas",
    cause: "Complexidade da base de dados legada",
    description: "Sistema legado possui estrutura não documentada que pode resultar em perda ou corrupção de dados durante a migração.",
    dimension: "Prazo",
    probabilityInitial: 3,
    severityScheduleInitial: 5,
    severityCapexInitial: 3,
    levelScheduleInitial: "Alto",
    levelCapexInitial: "Médio",
    levelGeneralInitial: "Alto",
    probabilitySchedule: 50,
    optimisticSchedule: 15,
    likelySchedule: 30,
    pessimisticSchedule: 60,
    weightedAverageSchedule: 32.5,
    expectedValueSchedule: 16.25,
    optimisticCapex: 80000,
    likelyCapex: 150000,
    pessimisticCapex: 300000,
    weightedAverageCapex: 163333,
    expectedValueCapex: 81667,
    probabilityResidual: 2,
    severityScheduleResidual: 3,
    severityCapexResidual: 2,
    levelScheduleResidual: "Médio",
    levelCapexResidual: "Baixo",
    levelGeneralResidual: "Médio",
    owner: "Pedro Almeida",
    status: "Monitorando",
    actions: [
      createAction("act-003-1", "Mitigar", "Pedro Almeida", "Concluída", -20),
      createAction("act-003-2", "Aceitar", "Carlos Oliveira", "Em Execução", -5),
    ],
    createdAt: "2025-09-25",
    updatedAt: "2025-10-14",
  },
  {
    id: "risk-004",
    projectId: "prj-alpha",
    type: "Ambiental",
    phase: "Licenciamento",
    disc: "AMB",
    seq: 3,
    code: "ALPHA-AMB-003",
    discipline: "Meio Ambiente",
    subject: "Licenças",
    title: "Atraso na obtenção da licença ambiental",
    cause: "Processo burocrático e período de chuvas",
    description: "Órgão ambiental pode demorar mais que o previsto para emitir licença de instalação devido à necessidade de estudos complementares.",
    dimension: "Prazo",
    probabilityInitial: 4,
    severityScheduleInitial: 5,
    severityCapexInitial: 2,
    levelScheduleInitial: "Crítico",
    levelCapexInitial: "Baixo",
    levelGeneralInitial: "Crítico",
    probabilitySchedule: 65,
    optimisticSchedule: 30,
    likelySchedule: 60,
    pessimisticSchedule: 120,
    weightedAverageSchedule: 65,
    expectedValueSchedule: 42.25,
    optimisticCapex: 30000,
    likelyCapex: 60000,
    pessimisticCapex: 100000,
    weightedAverageCapex: 63333,
    expectedValueCapex: 41167,
    probabilityResidual: 2,
    severityScheduleResidual: 4,
    severityCapexResidual: 2,
    levelScheduleResidual: "Médio",
    levelCapexResidual: "Baixo",
    levelGeneralResidual: "Médio",
    owner: "Carlos Oliveira",
    status: "Aberto",
    actions: [
      createAction("act-004-1", "Mitigar", "Carlos Oliveira", "Em Execução", -3),
    ],
    createdAt: "2025-10-01",
    updatedAt: "2025-10-17",
  },
  {
    id: "risk-005",
    projectId: "prj-beta",
    type: "Operacional",
    phase: "Treinamento",
    disc: "RH",
    seq: 2,
    code: "BETA-RH-002",
    discipline: "Recursos Humanos",
    subject: "Capacitação",
    title: "Resistência dos usuários ao novo sistema",
    cause: "Mudança de processos estabelecidos",
    description: "Usuários acostumados com sistema antigo podem resistir à mudança, impactando a adoção e efetividade do novo sistema.",
    dimension: "Ambos",
    probabilityInitial: 3,
    severityScheduleInitial: 3,
    severityCapexInitial: 3,
    levelScheduleInitial: "Médio",
    levelCapexInitial: "Médio",
    levelGeneralInitial: "Médio",
    probabilitySchedule: 60,
    optimisticSchedule: 10,
    likelySchedule: 20,
    pessimisticSchedule: 40,
    weightedAverageSchedule: 21.67,
    expectedValueSchedule: 13,
    optimisticCapex: 40000,
    likelyCapex: 80000,
    pessimisticCapex: 150000,
    weightedAverageCapex: 85000,
    expectedValueCapex: 51000,
    probabilityResidual: 1,
    severityScheduleResidual: 2,
    severityCapexResidual: 2,
    levelScheduleResidual: "Baixo",
    levelCapexResidual: "Baixo",
    levelGeneralResidual: "Baixo",
    owner: "Ana Costa",
    status: "Monitorando",
    actions: [
      createAction("act-005-1", "Mitigar", "Ana Costa", "Concluída", -15),
      createAction("act-005-2", "Aceitar", "Pedro Almeida", "Em Execução", 0),
    ],
    createdAt: "2025-10-05",
    updatedAt: "2025-10-16",
  },
  {
    id: "risk-006",
    projectId: "prj-alpha",
    type: "Fornecedor",
    phase: "Contratação",
    disc: "SUP",
    seq: 4,
    code: "ALPHA-SUP-004",
    discipline: "Suprimentos",
    subject: "Fornecedores",
    title: "Falência de fornecedor crítico",
    cause: "Instabilidade financeira do setor",
    description: "Fornecedor principal de componentes estruturais apresenta sinais de dificuldades financeiras que podem levar à interrupção do fornecimento.",
    dimension: "Ambos",
    probabilityInitial: 2,
    severityScheduleInitial: 5,
    severityCapexInitial: 4,
    levelScheduleInitial: "Médio",
    levelCapexInitial: "Médio",
    levelGeneralInitial: "Médio",
    probabilitySchedule: 30,
    optimisticSchedule: 20,
    likelySchedule: 45,
    pessimisticSchedule: 90,
    weightedAverageSchedule: 48.33,
    expectedValueSchedule: 14.5,
    optimisticCapex: 100000,
    likelyCapex: 200000,
    pessimisticCapex: 400000,
    weightedAverageCapex: 216667,
    expectedValueCapex: 65000,
    probabilityResidual: 1,
    severityScheduleResidual: 3,
    severityCapexResidual: 3,
    levelScheduleResidual: "Baixo",
    levelCapexResidual: "Baixo",
    levelGeneralResidual: "Baixo",
    owner: "Pedro Almeida",
    status: "Monitorando",
    actions: [
      createAction("act-006-1", "Evitar", "Pedro Almeida", "Concluída", -25),
      createAction("act-006-2", "Transferir", "Carlos Oliveira", "Concluída", -10),
    ],
    createdAt: "2025-10-08",
    updatedAt: "2025-10-12",
  },
];
